FROM wurstmeister/kafka:latest
EXPOSE 9092

ENV KAFKA_ZOOKEEPER_CONNECT=zookeeper-service:2181
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-service:9092
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

CMD ["start-kafka.sh"]
